---
title: "Comparative Analysis of Different Outlier Methods"
author: "Priyanga Dilini talagala"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
     toc: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(HDoutliers)
library(stray)
#library(purrr)
#library(tidyverse)
#library(gridExtra)
# install.packages("devtools")
# devtools::install_github("pridiltal/stray")
library(stray)
```

## Introduction
`stray` is an R package to detect outlirs in High dimensional data. This algorithm is motivatd from \code{\link[HDoutliers]{HDoutliers}} package. In `stray` we define an anomaly as an obervation or a cluster of observation  that displays a significant deviation from the majority.  An approach based on extreme value theory is used to define an anomalous threshold.

## A comparative analysis with `HDoutliers` package (Wilkinson, 2018)

Eventhough our main focus is on high dimensional data, for simplicity, we use two-dimensional problems to demonstrate the special features of our algorithm.



## References
Wilkinson, L. (2018). Visualizing Big Data Outliers through Distributed Aggregation. IEEE transactions on visualization and computer graphics, 24(1), 256-266.
